from pydantic_settings import BaseSettings
from pydantic import ConfigDict
from functools import lru_cache
from typing import List


class Settings(BaseSettings):
    model_config = ConfigDict(env_file=".env", env_file_encoding="utf-8")

    # App
    app_name:    str  = "HRI Explainable Behaviour Platform"
    app_version: str  = "1.0.0"
    environment: str  = "development"
    debug:       bool = False

    # Security
    secret_key:                  str = "hri-platform-secret-change-in-production"
    access_token_expire_minutes: int = 30
    refresh_token_expire_days:   int = 7

    # First admin account — auto-seeded on startup only if the user table is
    # empty. Change these before deploying anywhere beyond local testing.
    first_admin_email:    str = "admin@lincoln.ac.uk"
    first_admin_name:     str = "Admin"
    first_admin_password: str = "ChangeMe123!"

    # Database
    database_url: str = "sqlite+aiosqlite:///./data/hri.db"

    # Ollama / VLM
    ollama_base_url:     str = "http://localhost:11434"
    vlm_model:           str = "llama3.2-vision:11b"   # new default
    vlm_timeout_seconds: int = 600

    # Generation limits — tuned down by default for slow/CPU-only hardware.
    # On faster hardware (GPU, or a lab machine), raise these in .env — no
    # code change needed. num_ctx: prompt actually runs ~1600-1700 tokens,
    # so 8192 was mostly unused KV-cache overhead on every single frame.
    # num_predict: observed completions run 400-900 tokens for this JSON
    # schema; lower ceiling still comfortably covers real responses.
    vlm_num_ctx:     int = 3072
    vlm_num_predict: int = 550

    # All models accepted by the pipeline — validated in the analysis endpoint
    allowed_vlm_models: List[str] = [
        # Tier 1 — best for HRI analysis
        "llava:13b",
        "llama3.2-vision:11b",
        "qwen2.5vl:7b",
        "internvl2.5:8b",
        # Tier 2 — balanced speed/quality
        "llava-llama3:8b",
        "minicpm-v:latest",
        "moondream2",
        # Tier 3 — lightweight / experimental
        "gemma4",
        "llava:7b",
        # Additional variants users may pull
        "llava:latest",
        "llama3.2-vision:latest",
        "qwen2.5vl:latest",
        "qwen2.5vl:72b",
        "internvl2.5:latest",
        "internvl2.5:26b",
        "llava-llama3:latest",
        "gemma4:latest",
        "moondream2:latest",
    ]

    # File upload
    upload_dir:               str       = "./uploads"
    max_upload_size_mb:       int       = 2048
    allowed_video_extensions: List[str] = [".mp4", ".avi", ".mov", ".mkv", ".webm"]

    # CORS
    cors_origins: str = "http://localhost:3000"

    # Clinical compliance
    nice_esf_disclaimer: str = (
        "⚠ CLINICAL DISCLAIMER (NICE ESF Tier D): This output is generated by an "
        "AI system and is intended solely for research purposes. It must not be used "
        "for clinical diagnosis, treatment decisions, or any direct patient care. "
        "All outputs require review by a qualified clinician. This system has not "
        "been validated as a medical device under UKCA/CE marking requirements."
    )

    @property
    def cors_origins_list(self) -> List[str]:
        return [o.strip() for o in self.cors_origins.split(",")]

    @property
    def max_upload_size_bytes(self) -> int:
        return self.max_upload_size_mb * 1024 * 1024

    def is_allowed_model(self, model: str) -> bool:
        """
        Accept any model the user selects.
        We validate loosely — if it ends with a known base name, allow it.
        This lets users pull variants like llava:13b-v1.6 etc.
        """
        if model in self.allowed_vlm_models:
            return True
        # Accept any variant of a known base (e.g. llava:13b-v1.6)
        known_bases = [
            "llava", "llama3.2-vision", "qwen2.5vl", "internvl2.5",
            "llava-llama3", "minicpm-v", "moondream", "gemma4",
        ]
        return any(model.startswith(base) for base in known_bases)


@lru_cache()
def get_settings() -> Settings:
    return Settings()